#!/bin/bash

max_size=0
file=$1

while [ ! -f "$file" ]; do
 # busy wait ...
 :
done

inotifywait -m -e modify -e close "$file" | while read -r events; do
if [[ "$events" == *CLOSE* ]]; then
  echo "$file CLOSED"
  exit 0
fi

current_size=$(stat -c%s "$file")
if [ $? != 0 ]; then
  echo "$file stat failed"
  exit 1
fi

if [ "$current_size" -gt "$max_size" ]; then
  max_size=$current_size
fi
echo "current_size:$current_size max_size:$max_size"
done
